### ISSUE TITLE
only languageFile and file-version options are generated in config.yml

### ISSUE THREAD

**Issue by ArkadSt** [nickuc/OpeNLogin#1]
My config.yml (made it txt so I could upload it)
[config.yml.txt](https://github.com/nickuc/OpeNLogin/files/5323372/config.yml.txt)

**Comment by nickuc** [comment]
Hello, @ArkadSt!
OpeNLogin is very simple for now, and doesn't have such a large config.yml yet.

I recommend using nLogin for more features:
https://nickuc.com/en/#plugins
