### ISSUE TITLE
Problem deleting plugin and folder with server login message

### ISSUE THREAD

**Issue by fk0ne** [nickuc/OpeNLogin#101]
I have tried the OpeNLogin plugin and now once I have deleted both the folder and the plugin once I log in to the server I get the message popping up on the screen, any way to fix it?
![2023-08-01_16 01 32](https://github.com/nickuc/OpeNLogin/assets/139928991/7974ffbf-d889-4c1b-ab38-c4043ed4f276)

**Comment by nickuc** [comment]
Hi, @fk0ne!

Check the message sent in chat and answer it.
