### ISSUE TITLE
NLogin not working with geyser users

### ISSUE THREAD

**Issue by WoomyCatow** [nickuc/OpeNLogin#105]
hi, today i wanted to make a server for java and bedrock and i wanted to add this plugin since i used it before and i liked how simple it was to set up, but now after i installed it, ive ran into various issues when login in with bedrock using geyser in aternos, the mod disconnects me from the server whenever i join and it drops a error that says "Sorry, but you are using an invalid nickname" and as i said before, i used this plugin with a geyser server and it didnt gave any problems, normally bedrock players with geyser gets a " . " in the name, is there any way to fix it? thanks
![image](https://github.com/nickuc/OpeNLogin/assets/147578858/f7afc4ba-0c99-4d25-ae29-6651e53047fe)

**Comment by nickuc** [comment]
Hi, @WoomyCatow 

Try to install Floodgate in your server as well and check if the problem is solved.
