### ISSUE TITLE
Sugestões nchat

### ISSUE THREAD

**Issue by xEll3si** [nickuc/OpeNLogin#108]
Adicionar na config nchat(do chat próprio) um comando para se travar o chat em vez de fazer /focus nomedochat
é muito chato ter de se fazer isso cada vez que se tem de travar, e existem inumeros plugins que usam por exemplo o mcmmo tem o admin chat que é só fazer /a  para travar e/ou falar    o que é uma maravilha.

E a outra sugestão seria com o nchat também, dar um broadcast a todos os servidores quando um novo jogador entra, mensagem personalizada por nós, sendo possivel ativar ou não a função.

Obrigado pela atenção ♥

**Comment by nickuc** [comment]
Olá, @xEll3si 

Sugiro que faça a sugestão por meio do nosso grupo do Discord
