### ISSUE TITLE
Edit|Reset account password

### ISSUE THREAD

**Issue by meshoksnega** [nickuc/OpeNLogin#112]
Hi guy who reading this.
I got some problems with passwords, and i wanna **Edit|Reset** pass of player

How i can do it? Because /unregister <PlayerNick> don't work

So i need help

![image](https://github.com/nickuc/OpeNLogin/assets/70194485/9629c954-a1fd-492e-8455-fd670209126d)

**Comment by nickuc** [comment]
Hi, @meshoksnega 

Have you tried to use `nlogin unregister <player>` instead? (if you are using nLogin)

**Comment by meshoksnega** [comment]
Let me try

**Comment by meshoksnega** [comment]
Still have problem
![image](https://github.com/nickuc/OpeNLogin/assets/70194485/df10444e-7523-495f-a791-f208f0524549)

**Comment by meshoksnega** [comment]
I got Nlogin on my server

![2024-04-23_07 31 50](https://github.com/nickuc/OpeNLogin/assets/70194485/f6100b01-9805-4fd6-bf7a-1dcc4a3cc3a1)

**Comment by meshoksnega** [comment]
So @nickuc what i can do?

**Comment by nickuc** [comment]
Hi, @meshoksnega 

Try running on the console instead again.

`nlogin unregister <player>`

**Comment by meshoksnega** [comment]
![image](https://github.com/nickuc/OpeNLogin/assets/70194485/ab41216c-378f-4d03-b898-da97e98febe1)
Trying so much times but it don't work


@nickuc

**Comment by nickuc** [comment]
What appears if you just run `nlogin` in the console?

**Comment by meshoksnega** [comment]
Idk how but it typing this 
![image](https://github.com/nickuc/OpeNLogin/assets/70194485/b1538ff9-096c-4a1e-869e-43fbebda665c)

But i got all files with Nlogin 
![image](https://github.com/nickuc/OpeNLogin/assets/70194485/cf46fa29-3b74-4e8a-b28d-2009634525b2)
![image](https://github.com/nickuc/OpeNLogin/assets/70194485/ccab89d8-03d5-4b84-a45c-c2be1301aa32)

**Comment by meshoksnega** [comment]
But when i typing this on server it works

**Comment by meshoksnega** [comment]
![2024-04-23_07 41 15](https://github.com/nickuc/OpeNLogin/assets/70194485/15900b53-a7dd-4e5a-a23a-f7d210a9e0f2)

**Comment by nickuc** [comment]
Are you using some kind of proxy server? (Velocity, BungeeCord, Waterfall)

- **If yes**, run this command on the proxy server instead.
- **If not**, try removing the other plugins and leaving only nLogin installed and restarting the server.

**Comment by meshoksnega** [comment]
Oh yes i'm using proxy😂
Bungeecord and in bungee console it work, thx so much
