### ISSUE TITLE
If I don't login and disconnect and go to another server/ singleplayer the login screen still shows up

### ISSUE THREAD

**Issue by boomerangos** [nickuc/OpeNLogin#17]
![2021-01-17_17 57 02](https://user-images.githubusercontent.com/71942224/104864348-8f52e500-58ed-11eb-9eba-4c60e1cf77f0.png)

I disconnected from a server with this plugin installed
I joined another server that has never had this plugin and the login screen appears
this occurs even in single player

**Comment by nickuc** [comment]
Hi, @boomerangos!

I will fix this bug.

**Comment by algj** [comment]
This is Minecraft bug, I had the same issue with other plugins.

**Comment by nickuc** [comment]
> This is Minecraft bug, I had the same issue with other plugins.

I thought I could solve it, but I forgot that Minecraft does not send any packet when the player disconnects.

Thank you very much for your information!

**Comment by algj** [comment]
This is a really annoying bug, the only solution is to restart Minecraft (not sure if joining other server with action bar helps).
It is quite a rare bug, personally only happened to me once.
I was not able to find it on bugs.mojang.com.

**Comment by nickuc** [comment]
> This is a really annoying bug if it happens, the only solution is to restart Minecraft (not sure if joining other server with /title helps, probably not).
> It is quite a rare bug, personally only happened to me once.
> I was not able to find it on bugs.mojang.com.

It really is a very strange bug. It seems to happen only when the title duration is long.
