### ISSUE TITLE
MINECRAFT 1.16.5 (ERROR)

### ISSUE THREAD

**Issue by uRyanxD** [nickuc/OpeNLogin#20]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.nickuc.report.?$???$??????? (file:/C:/Users/User/Desktop/Project%20Lazarus/plugins/nReport.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of com.nickuc.report.?$???$???????
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by nickuc** [comment]
Hi, @uRyanxD!

This is not an error, but a warning. Illegal reflective operations will be denied in new versions of Java.
