### ISSUE TITLE
restart password command?

### ISSUE THREAD

**Issue by teleguest** [nickuc/OpeNLogin#28]
how to restart password ?

**Comment by nickuc** [comment]
Hi, @teleguest!

If you want to reset the password of a member of your server, use the follow commands:

**nLogin:**
Perform the command nlogin unregister <player> [in the console]

**OpeNLogin:**
Perform the command unregister <player> [in the console].

**Comment by teleguest** [comment]
thank you

**Comment by JgBr123** [comment]
> Hi, @teleguest!
> 
> If you want to reset the password of a member of your server, use the follow commands:
> 
> **nLogin:** Perform the command `nlogin unregister <player>` [in the console]
> 
> **OpeNLogin:** Perform the command `unregister <player>` [in the console].

Unknown command. Type "/help" for help.

**Comment by nickuc** [comment]
> > Hi, @teleguest!
> > If you want to reset the password of a member of your server, use the follow commands:
> > **nLogin:** Perform the command `nlogin unregister <player>` [in the console]
> > **OpeNLogin:** Perform the command `unregister <player>` [in the console].
> 
> Unknown command. Type "/help" for help.
You are probably using another authentication plugin or OpeNLogin/nLogin is not loaded.

**Comment by JgBr123** [comment]
Everythings works fine, except for unregister

**Comment by nickuc** [comment]
> Everythings works fine, except for unregister (and i dont have any other auth plugin loaded)

Check if you are running OpeNLogin v1.5.2
https://github.com/nickuc/OpeNLogin/releases/tag/v1.5.2
