### ISSUE TITLE
Permament problem after deleting plugin

### ISSUE THREAD

**Issue by Silvobi** [nickuc/OpeNLogin#33]
I tried to unregister myself by deleting some lines from accounts.db/data.db file (I don't excacly remember it's name)
After that I wasn't be able to join server so I decied to delete the plugin. Now I can't move, unless I jump, and adding plugin again makes it doesn't work at all (it don't allow you move, but you can login or register)

**Comment by nickuc** [comment]
Hi, @Silvobi!

Backup your main world and delete the `stats` folder from within it.
