### ISSUE TITLE
Jak zmienić język

### ISSUE THREAD

**Issue by fifiyt556** [nickuc/OpeNLogin#39]
witam jestem początkujący i nie wiem jak zmiecić język na polski w waszym pluginie. w notatniku nie mogę znaleźć # Język wtyczki:
languageFile : więc wydaje mi się że to nie w nim.

**Comment by nickuc** [comment]
Hi, @fifiyt556!

Are you trying to change the language via config.yml? 
Could you send me your current config around here?
