### ISSUE TITLE
Simple feature request, so please make it fast. 

### ISSUE THREAD

**Issue by Aadi-mone** [nickuc/OpeNLogin#44]
This is A simple feature request.

Can you please add a feature like after doing /login password

In the config, we could set command so that we can execute a command like: tp {player} 78 45 321

so this will become a bungee tp login without bungee being installed.

Similar to tp login in bungee

Hope you adds it :)

**Comment by Aadi-mone** [comment]
and please reply even if you don't like or not, please reply

**Comment by nickuc** [comment]
Hi, @Aadi-mone!

Interesting idea. I'll add in a future update of OpenNLogin.

**Comment by nickuc** [comment]
#43

**Comment by Aadi-mone** [comment]
thanks nick,
and just one more question, will this take too long like a month or more?
because I requested this same feature in other plugins and no others replied like this.
this reply is really appreciated. 
and please notify me when done so I can rate the plugin 5 stars :)

**Comment by Aadi-mone** [comment]
thanks

**Comment by Aadi-mone** [comment]
@nickuc 
Hello nick, Hope you're doing well,
it has been a while, is the update complete or it will take more time?
I am waiting.
