### ISSUE TITLE
Reset an accounts password

### ISSUE THREAD

**Issue by a8underscore** [nickuc/OpeNLogin#5]
Hello we have a player who forget the password, we need to reset or unregester the player. we tried with the unregister command but it needs his password, we dont know it. we tried finding it in the DB but the passwords seem encrypted

Please help, thanks

**Comment by nickuc** [comment]
Hi, @a8underscore!

To unregister an user, perform the command **/unregister <player>** [console]

**Comment by a8underscore** [comment]
it says incorrect password when we would try /unregister *username*

**Comment by nickuc** [comment]
Are you executing the command through the console?

**Comment by a8underscore** [comment]
no

**Comment by nickuc** [comment]
Execute this command through the console.

**Comment by Fahim360** [comment]
Is there any other way to unregister?

**Comment by datpusheen123** [comment]
use /changepassword <username> in console

**Comment by nickuc** [comment]
> howdy , i got a bot that keeps my server 24/7 on does the plugin log out players who do not login ?

Yes, it disconnects the player.
