### ISSUE TITLE
is there anyway?

### ISSUE THREAD

**Issue by Aadi-mone** [nickuc/OpeNLogin#56]
is there any way for importing passwords from the login security plugin to this plugin? because my server has 78 players registered and their passwords and accounts will get hacked if I change it to your plugin so anyways? pls make this at least fast

**Comment by nickuc** [comment]
Hi, @Aadi-mone!

Unfortunately this converter is only available for **nLogin** for now, but I plan to add a conversion soon :)

nLogin: https://www.nickuc.com/repo/find?name=nLogin
