### ISSUE TITLE
[FATAL_BUG] Bungee command bypass

### ISSUE THREAD

**Issue by Rabkaleta** [nickuc/OpeNLogin#59]
I can use bungee command, even before I login
![2021-12-20_06 36 45](https://user-images.githubusercontent.com/84437677/146695056-c60216d2-fa90-4176-a3ab-b2cd464ee2aa.png)

**Comment by Rabkaleta** [comment]
i can just use /server to bypass login

**Comment by Rabkaleta** [comment]
![2021-12-20_06 51 55](https://user-images.githubusercontent.com/84437677/146695366-388fa57d-54c3-45f3-a6ce-e6f8079b077b.png)

**Comment by nickuc** [comment]
Hi, @Rabkaleta!

You need to configure BungeeGuard:
https://www.nickuc.com/docs/bungeeguard
