### ISSUE TITLE
Invalid name when using Floodgate

### ISSUE THREAD

**Issue by Spas-Nikolaev-Dimitrov** [nickuc/OpeNLogin#66]
Hello I tried to enable bedrock clients to join to my minecraft server, but when they try to join a message pops up and saying that the name is illegal, because of floodgate which changes the name for bedrock clients and adds a . at the start, how can I enable illegal names on my server?

**Comment by Reinmmar** [comment]
You can try disabling online mode, which disables the name check for players. The downsides include that no skins are loaded

**Comment by nickuc** [comment]
Using the `*` prefix in Floodgate should resolve this issue.
