### ISSUE TITLE
Login timeout question

### ISSUE THREAD

**Issue by herkintm** [nickuc/OpeNLogin#68]
i want to have longer login i changed to 300 and i still have 60

**Comment by nickuc** [comment]
Hi, @herkintm!

- Probably your config.yml is outdated
- Or you are using nLogin and got confused with the OpeNLogin folder. _(use plugins/nLogin instead)_

**Comment by herkintm** [comment]
how to do it

**Comment by herkintm** [comment]
ok got it but where i can change time to have longer login

**Comment by herkintm** [comment]
hello? how i can put login to longer?

**Comment by nickuc** [comment]
> hello? how i can put login to longer?

Please check the config.yml file

**Comment by herkintm** [comment]
he the nlogin files and where i can change?

**Comment by herkintm** [comment]
comfig i dont see it in config
