### ISSUE TITLE
OpenNLogin doesn't do proper name filtering.

### ISSUE THREAD

**Issue by KamenkoTV** [nickuc/OpeNLogin#7]
Theres a player that joined on my server with name **Stef_fort_2007 .** and apparently OpenNLogin allowed him to join with that name even tho he has space and a dot in the name i don't know did he use zero space or any blank characters, but i know that there is a problem banning him i have already banned him using ip ban but he keeps avoiding ban using VPN if i try banning him using name here's what i get.
`Player 7dr banned Stef_fort_2007 . for: .`
and if i try doing ban command like this in quotes /ban "Stef_fort_2007 ."
i just get this
`Player 7dr banned Stef_fort_2007 . for: ."`
because he has space in name..
OpenNLogin shouldn't allow such names to connect to the server.

the screenshot: https://i.imgur.com/Q1pglde.png

**Comment by nickuc** [comment]
Hi @KamenkoTV!

Thanks for your bug report!
An error correction has been made available.

Download: https://github.com/nickuc/OpeNLogin/releases
