### ISSUE TITLE
translation problem

### ISSUE THREAD

**Issue by Sebayop** [nickuc/OpeNLogin#8]
the text of the time remaining for the login does not change if the language is changed.
![javaw_lMHmwPH0CL](https://user-images.githubusercontent.com/69135014/98429104-88089300-2083-11eb-9e1a-b8219257ca34.png)

**Comment by nickuc** [comment]
Hi @Sebayop!

Thanks for your bug report!
An error correction has been made available.

Download: https://nickuc.com/repo/find?name=nLogin
