### ISSUE TITLE
Fail2ban configuration file.

### ISSUE THREAD

**Issue by GamePlayer-8** [nickuc/OpeNLogin#83]
Heyo,

How should I configure RegEx filter in Fail2ban in order to protect server from massive login attempts?

**Comment by nickuc** [comment]
Hi, @GamePlayer-8!

I don't think this is related to OpeNLogin

**Comment by GamePlayer-8** [comment]
Oh, I though that OpeNLogin is sending `Incorrect password` disconnect messages:
```log4j
[08:38:27] [Server thread/INFO]: GamePlayer[/192.168.0.70:34232] logged in with entity id 573 at ([world]-99.20124976516018, 71.48903121179275, -99.66204703718567)
[08:38:52] [Server thread/INFO]: GamePlayer lost connection: Incorrect password. Please, try again.
```

**Comment by nickuc** [comment]
> Oh, I though that OpeNLogin is sending `Incorrect password` disconnect messages:
> 
> ```
> [08:38:27] [Server thread/INFO]: GamePlayer[/192.168.0.70:34232] logged in with entity id 573 at ([world]-99.20124976516018, 71.48903121179275, -99.66204703718567)
> [08:38:52] [Server thread/INFO]: GamePlayer lost connection: Incorrect password. Please, try again.
> ```

But what does it have to do with Fail2ban?

**Comment by GamePlayer-8** [comment]
Fail2ban would read the `logs/latest.log` file & check for those values in order to count login attempts failure.

Fail2ban is basically protecting from bruteforce attacks or bot attacks.

**Comment by nickuc** [comment]
> Fail2ban would read the `logs/latest.log` file & check for those values in order to count login attempts failure.
> 
> Fail2ban is basically protecting from bruteforce attacks or bot attacks.

There is no such feature, you would need to modify code to support this

**Comment by GamePlayer-8** [comment]
I guess, adding one line of code (console.log?) with content like:
 - `Player`;
 - `IP`;
 - `Login failure`.
 Is enough to support Fail2ban.
