### ISSUE TITLE
Password Change

### ISSUE THREAD

**Issue by Safwan47** [nickuc/OpeNLogin#84]
how to change password if u dont remember ur password?

**Comment by nickuc** [comment]
Hi, @Safwan47!

You can remove password instead. Type `unregister <player>` in console.

**Comment by siriozo** [comment]
it doesnt work

**Comment by siriozo** [comment]
we are doing it trought the console but it just doesnt work

**Comment by nickuc** [comment]
> we are doing it trought the console but it just doesnt work

If you are using nLogin, run `nlogin unregister <player` instead.
