### ISSUE TITLE
Can you add additional authorization type

### ISSUE THREAD

**Issue by sqwaka** [nickuc/OpeNLogin#88]
Most pirate servers use the usual command /reg | /log <password>. Can add additional information by password, login for example. 

Example: 
/reg <login> <password> <password>
/login <login> <password>

And output the function to an additional login in the configuration file 

use-additionaly-login: “true|false”

**Comment by nickuc** [comment]
This has already been added to plugin.yml, are you sure it's not another plugin blocking it?

https://github.com/nickuc/OpeNLogin/blob/1ce258b1149a3508b70611fc124735952bdaf17b/openlogin-bukkit/src/main/resources/plugin.yml#L8

**Comment by sqwaka** [comment]
No, you misunderstood. It was meant to add an additional login

/reg login password password
/login login password 

on most pirate servers, passwords are often picked up and it turns out that another user is playing. if you add an additional login, be cool, but add it as a separate function that can be adjusted in the file (whether it works or not)

**Comment by nickuc** [comment]
> No, you misunderstood. It was meant to add an additional login
> 
> /reg login password password /login login password
> 
> on most pirate servers, passwords are often picked up and it turns out that another user is playing. if you add an additional login, be cool, but add it as a separate function that can be adjusted in the file (whether it works or not)

I couldn't quite understand what you meant. Would it be a 2FA system using another password?

**Comment by sqwaka** [comment]
By the type of
