### ISSUE TITLE
I want to be a translator

### ISSUE THREAD

**Issue by KamenkoTV** [nickuc/OpeNLogin#9]
Hi i would like to help translating the plugin into 
Serbian, Croatian, Bosnian, and Montenegrian,
I'm Native in these languages,

do i just need to just submit the messages_rs.yml file?

**Comment by nickuc** [comment]
Hi @KamenkoTV!

Thank you for your interest in contributing to OpeNLogin! ;)

1. To submit the translated file, go to https://github.com/nickuc/OpeNLogin/tree/master/openlogin-common/src/main/resources/com/nickuc/openlogin/config/lang
2. After that, click the 'Add file'->'Create new file' button (https://i.imgur.com/qcjn400.png)
3. Choose a name for the file, paste the content of the translation and click on 'Propose changes' (https://i.imgur.com/YfitJEv.png)
4. Click the 'Create pull request' button

**Comment by KamenkoTV** [comment]
Thanks for the quick reply!
I have successfully contributed.
